### ISSUE TITLE
Invenio Documentation

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/DataRepositoryConnector#5]
Please update the [existing documentation](https://omeka.org/s/docs/user-manual/modules/datarepositoryconnector/) with instructions/specific options for Invenio. Thanks!

**Comment by allanaaa** [comment]
I'll take this one; I want to do some more general work on this page. 

Is there any chance that the module can have some content on the "Past imports" page, instead of a blank page that comes up when you click on the name or the plus sign? 

We're not really very consistent on this front; other modules that have a "Past X" page range from blank to something like this, which would be preferable:
![datacleaning](https://user-images.githubusercontent.com/28012148/210647576-69d8996b-bf38-4671-b2fe-12f34825c769.PNG)

This is the only module that uses the blank "Past X" page as the splash page.

(I realize this opens up a design can-of-worms for a bunch of other modules...)

**Comment by katknow** [comment]
@allanaaa let me know if I can help out in any way

**Comment by matthewjmckinley** [comment]
@allanaaa the "There are no past imports" text and graphic should show up with the latest commit.

As far as adding it to other modules with Past Jobs/Imports, it's a fairly trivial few lines from the code side. I think you're right that we'd want to make sure everything matches design-wise, but that shouldn't be too hard either.

**Comment by allanaaa** [comment]
Thanks. Is this coming out with the 4.0 version, now that the testing is done?

**Comment by matthewjmckinley** [comment]
I think that's the plan. Are you still encountering DRC/DSpace import bugs with the latest rc version?

**Comment by allanaaa** [comment]
DSpace worked and Invenio worked; I need to test out the others again.
